### ISSUE TITLE
dgcd and dgco are the same

### ISSUE THREAD

**Issue by paulirish** [sh1boot/numderline#3]
Across several different fonts I don't see a difference between these two.

btw absolutely love your work on this project and the direction you took it from tristan's.

**Comment by sh1boot** [comment]
Oops.  Yeah, sorry, it looks like I commented out a line by accident while testing.  Fixed now.

I think at some point I'm going to have to refactor this more deeply so that decimal policy is entirely separate from whole number policy, because there are so many different permutations to conider otherwise.  For example, I notice that Wikipedia has a standard group of five digits for decimals and three for whole numbers.

But it's one of so many things to get around to...
